Add support for GeoJSON Number Identifiers
Outdooractive/gis-tools pull request #7
Opened 2023-04-05 01:20 UTC by sena-mike

[Problem]
* Currently the package does not support parsing the identifier field from GeoJSON at all.
* Also it only models the id as `String`

[Solution]
* Parse `"id"` from the JSON.
* Introduce `Identifier` enum that models `String`/`Int`/`Double` based identifiers.

[Testing]
* Updated unit tests.

2023-04-05 10:06 UTC, trasch requested changes
Thanks a lot for this change, this is a real improvement!

Please don't feel offended by my code style change requests, all my colleagues get that too... 😄

2023-04-05 10:06 UTC, trasch commented on Tests/GISToolsTests/GeoJson/FeatureTests.swift
> +        let feature = Feature(Point(.zero))
I would propose to add an `id` here and check that it's of the proper type in the result JSON, like

```
        let feature = Feature(Point(.zero), id: .int(5))
        ...
        XCTAssertEqual(json["id"] as? Int, 5)
```

2023-04-05 19:37 UTC, sena-mike commented on Sources/GISTools/GeoJson/Feature.swift
> +        var jsonValue: Any {
I'll go ahead and change to to `asJson` here and there can be a single pass to refactor the naming.

2023-04-05 19:39 UTC, sena-mike commented on Sources/GISTools/GeoJson/Feature.swift
> +        self.id = Identifier(value: geoJson["id"])
Updated nice catch on the bug

2023-04-06 09:22 UTC, trasch approved these changes

2023-04-06 09:24 UTC, merged